# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/untitled2/untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import gui.untitled2.resources

class Ui_Login_page(object):
    def setupUi(self, Login_page):
        Login_page.setObjectName("Login_page")
        Login_page.setWindowModality(QtCore.Qt.ApplicationModal)
        Login_page.resize(1162, 582)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        Login_page.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix1/phenom_logo_2.JPEG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Login_page.setWindowIcon(icon)
        Login_page.setStyleSheet("")
        Login_page.setWindowFilePath("")
        self.frame = QtWidgets.QFrame(Login_page)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1161, 581))
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setMouseTracking(True)
        self.frame.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.frame.setStyleSheet("background-image: url(:/new/prefix1/Login_page.png);\n"
"/*background-attachment: fixed;*/\n"
"background-color: transparent;")
        self.frame.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.register_button = QtWidgets.QPushButton(self.frame)
        self.register_button.setGeometry(QtCore.QRect(460, 410, 291, 81))
        self.register_button.setStyleSheet("QPushButton\n"
"{\n"
"background-image: url(:/new/prefix1/registerbutton.png);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-image: url(:/new/prefix1/registerbutton.png);\n"
"border: 0px\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-image: url(:/new/prefix1/registerbutton.png);\n"
"margin: 2px;\n"
"}\n"
"")
        self.register_button.setText("")
        self.register_button.setFlat(True)
        self.register_button.setObjectName("register_button")
        self.close_bt = QtWidgets.QPushButton(self.frame)
        self.close_bt.setGeometry(QtCore.QRect(980, 10, 31, 31))
        self.close_bt.setStyleSheet("QPushButton\n"
"{\n"
"border-image: url(:/new/prefix1/close_icon.png);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-image: url(:/new/prefix1/close_icon.png);\n"
"border: 0px\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border-image: url(:/new/prefix1/close_icon.png);\n"
"margin: 2px;\n"
"}\n"
"")
        self.close_bt.setText("")
        self.close_bt.setObjectName("close_bt")
        self.minize_bt = QtWidgets.QPushButton(self.frame)
        self.minize_bt.setGeometry(QtCore.QRect(940, 10, 31, 31))
        self.minize_bt.setStyleSheet("QPushButton\n"
"{\n"
"border-image: url(:/new/prefix1/minimize_icon.png);\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-image: url(:/new/prefix1/minimize_icon.png);\n"
"border: 0px\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border-image: url(:/new/prefix1/minimize_icon.png);\n"
"margin: 2px;\n"
"}\n"
"")
        self.minize_bt.setText("")
        self.minize_bt.setFlat(True)
        self.minize_bt.setObjectName("minize_bt")
        self.email_le = QtWidgets.QLineEdit(self.frame)
        self.email_le.setGeometry(QtCore.QRect(500, 210, 241, 41))
        self.email_le.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.email_le.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.email_le.setStyleSheet("QLineEdit {\n"
"        border: 2px solid rgb(0, 64, 129);\n"
"        background: rgb(0, 64, 129);\n"
"        color: rgb(255, 255, 255);\n"
"        background-color: rgb(0, 64, 129);\n"
"    }")
        self.email_le.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.email_le.setInputMask("")
        self.email_le.setText("")
        self.email_le.setMaxLength(200)
        self.email_le.setDragEnabled(True)
        self.email_le.setObjectName("email_le")
        self.licenseKey_le = QtWidgets.QLineEdit(self.frame)
        self.licenseKey_le.setGeometry(QtCore.QRect(500, 320, 241, 41))
        self.licenseKey_le.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.licenseKey_le.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.licenseKey_le.setStyleSheet("QLineEdit {\n"
"        border: 2px solid rgb(0, 64, 129);\n"
"        background: rgb(0, 64, 129);\n"
"        color: rgb(255, 255, 255);\n"
"        background-color: rgb(0, 64, 129);\n"
"    }")
        self.licenseKey_le.setInputMask("")
        self.licenseKey_le.setText("")
        self.licenseKey_le.setMaxLength(100)
        self.licenseKey_le.setDragEnabled(True)
        self.licenseKey_le.setObjectName("licenseKey_le")
        self.unsuccessfull_label = QtWidgets.QLabel(self.frame)
        self.unsuccessfull_label.setGeometry(QtCore.QRect(500, 380, 241, 17))
        self.unsuccessfull_label.setStyleSheet("QLabel\n"
"{\n"
"border: 2px solid rgb(0, 64, 129);\n"
"        background: rgb(0, 64, 129);\n"
"        color: rgb(255, 255, 255);\n"
"        background-color: rgb(0, 64, 129);\n"
"}")
        self.unsuccessfull_label.setText("")
        self.unsuccessfull_label.setObjectName("unsuccessfull_label")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(510, 60, 191, 141))
        self.label.setStyleSheet("QLabel\n"
"{\n"
"/*background: rgb(0, 64, 129);*/\n"
"    background-image: url(:/new/prefix1/pheno_logo.png);\n"
"/*background-color: rgb(0, 64, 129);*/\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Login_page)
        QtCore.QMetaObject.connectSlotsByName(Login_page)

    def retranslateUi(self, Login_page):
        _translate = QtCore.QCoreApplication.translate
        Login_page.setWindowTitle(_translate("Login_page", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login_page = QtWidgets.QWidget()
    ui = Ui_Login_page()
    ui.setupUi(Login_page)
    Login_page.show()
    sys.exit(app.exec_())
