from google_trans_new import google_translator
import sys
import difflib

text=sys.argv[1]
destination=sys.argv[2]

sting = destination.strip().lower().replace("'", '')
destinations_dict={
    'afrikaans' : 'af',
    'Amharic' : 'am',
    'arabic	' : 'ar',
    'azerbaijani' : 'az',
    'belarusian'  : 'be',
    'bulgarian' : 'bg',
    'bosnian'   : 'bs',
    'catalan'   : 'ca',
    'cebuano'   : 'ceb',
    'corsican'  : 'co',
    'czech'     : 'cs',
    'welsh'     : 'cy',
    'danish'    : 'da',
    'german'    : 'de',
    'greek'     : 'el',
    'english'   : 'en',
    'esperanto' : 'eo',
    'spanish'   : 'es',
    'estonian'  : 'et',
    'basque'    : 'eu',
    "persian"   : "fa",
    'farsi'     : 'fa',
    'finnish'   : 'fi',
    'french'    : 'fr',
    'west frisian' : 'fy',
    'frysk'     : 'fy',
    'irish'     : 'ga',
    'scotish gaelic' : 'gd',
    'galician'  : 'gl',
    'gaelgo'    : 'gl',
    'gujarati'  : 'gu',
    'hausa'     : 'ha',
    'hawaiian'  : 'haw',
    'hindi'     : 'hi',
    'croatian'  : 'hr',
    'haitian'   : 'ht',
    'hungarian' : 'hu',
    'armenian'  : 'hy',
    'indonesian': 'id',
    'igbo'      : 'ig',
    'icelandic' : 'is',
    'italian'   : 'it',
    'japanese'  : 'ja',
    'georgian'  : 'ka',
    'kazakh'    : 'kk',
    'cambodian' : 'km',
    'kannad'    : 'kn',
    'korean'    : 'ko',
    'kurdish'   : 'ku',
    'kumanji'   : 'ku',
    'kirghiz'   : 'ky',
    'latin'     : 'la',
    'luxembourgish': 'lb',
    'laotian'   : 'lo',
    'lithuanian': 'lt',
    'latvian'   : 'lv',
    'malagasy'  : 'mg',
    'maori'     : 'mi',
    'macedonian': 'mk',
    'malayalam' : 'ml',
    'mongolian' : 'mn',
    'marathi'   : 'mr',
    'malay'     : 'ms',
    'maltese'   : 'mt',
    'burmese'   : 'my',
    'nepali'    : 'ne',
    'dutch'     : 'nl',
    'chihchewa' : 'ny',
    'oriya'     : 'or',
    'panjabi'   : 'pa',
    'polish'    : 'pl',
    'pashto'    : 'ps',
    'portuguese': 'pt',
    'romanian'  : 'ro',
    'russian'   : 'ru',
    'rwandi'    : 'rw',
    'sindhi'    : 'sd',
    'sinhalese' : 'si',
    'slovak'    : 'sk',
    'slovenian' : 'sl',
    'samon'     : 'sm',
    'shona'     : 'sn',
    'somalia'   : 'so',
    'albanian'  : 'sq',
    'serbian'   : 'sr',
    'sudanese'  : 'su',
    'swedish'   : 'sw',
    'tami'      : 'ta',
    'telugu'    : 'te',
    'turkmen'   : 'tk',
    'turkish'   : 'tr',
    'ukrainian' : 'uk',
    'urdu'      : 'ur',
    'uzbek'     : 'uz',
    'vietnamese': 'vi',
    'chinese'   : 'zh-CN',
    'zulu'      : 'zu',
    'فارسی'     : 'fa',
    'انگلیسی'   : 'en',
    'انگلیس'   : 'en',
    'فرانسه'   : 'fr',
    'آلمانی'    : 'de',
    'المانی'    : 'de',
     'آلمان'    : 'de',
    'المان'    : 'de',
    'اسپانیایی' : 'es',
    'یونانی'    : 'el',
    'چینی'      : 'zh-CN',
     'اسپانیا' : 'es',
    'یونان'    : 'el',
    'چین'      : 'zh-CN'
}

language_target = destinations_dict[destination.strip().lower().replace("'", '')].lower()
try:
    translator=google_translator()
    print(translator.translate(text.lower(), lang_tgt=language_target))
except:
    print("I can't find anything!")